language: node_js
node_js:
  - "lts/*"
services:
  - docker

before_install:
  - echo "Building docker images"
  - docker build -t devscesjsu/sce-core-backend-dev:staging -f ./docker/Dockerfile-serverjs
  - docker build -t devscesjsu/sce-core-frontend-dev:staging -f ./docker/Dockerfile-ScePage

# No testing yet.


install: true

deploy:
  - echo "Logging in to TreeScale" | docker login repo.treescale.com -u "$DOCKER_USERNAME" --password "$DOCKER_PASSWORD"
  - docker push repo.treescale.com/devscesjsu/sce-core-backend-dev:staging
  - docker push repo.treescale.com/devscesjsu/sce-core-frontend-dev:staging
