branches:
  only:
  - dev
  - joon/Travis

language: node_js
node_js:
  - "lts/*"
services:
  - docker

# Build in travis VM for testing
before_install:
  - echo "Building docker images"
  - docker build -t devscesjsu/sce-core-backend-dev:staging -f ./docker/Dockerfile-serverjs .
  - docker build -t devscesjsu/sce-core-frontend-dev:staging -f ./docker/Dockerfile-ScePage .

# No testing yet.

install: true

before_script:
  - echo "Skipping testing"

script:
  - echo "Skipping testing"


# Deploy, push to TreeScale for docker repo
deploy:
  provider: script
  script: bash deploy_to_treescale.sh
  on:
    branch: dev
