version: '3'
services:
  sce-main-endpoints-api:
    container_name: sce-main-endpoints-api
    build:
      context: ./api
      dockerfile: ./main_endpoints/Dockerfile
    ports:
      - '8080:8080'
    restart: 'on-failure'
    links:
      - mongodb
    networks:
      - sce-local
  sce-logging-api:
    container_name: sce-logging-api
    build:
      context: ./api
      dockerfile: ./logging_api/Dockerfile
    ports:
      - '8081:8081'
    restart: 'on-failure'
    links:
      - mongodb
    networks:
      - sce-local
  sce-google-api:
    container_name: sce-google-api
    build:
      context: ./api
      dockerfile: ./google_api/Dockerfile
    ports:
      - '8082:8082'
    restart: 'on-failure'
    links:
      - mongodb
    networks:
      - sce-local
  frontend:
    container_name: sce-frontend
    build:
      context: .
      dockerfile: ./Dockerfile
    ports: 
      - '3000:80'
    links:
      - sce-main-endpoints-api
      - sce-logging-api
      - sce-google-api
    networks:
      - sce-local
  mongodb:
    container_name: db
    image: mongo
    volumes:
      - "~/data/db:/usr/src/app/data/db"
    ports: 
      - '27017:27017'
    networks:
      - sce-local
networks:
  sce-local:
      driver: bridge
